### ISSUE TITLE
Backward compatibility with older Oscar2013Extended versions

### ISSUE THREAD

**Issue by Hendrik1704** [smash-transport/sparkx#132]
We should implement backward compatibility with older Oscar2013Extended versions. At least for the versions before strangeness and baryon number were added.

This was already mentioned in PR #131.

**Comment by NGoetz** [comment]
A consequence of this is also that misleading error messages are shown. Throwing post #131 sparkx on the IC output with baryon number, but without strangeness, gives the error message "baryon number not set" because I think it did not recognise the extended OSCAR output.

**Comment by Hendrik1704** [comment]
Ok, that's something we should take a look at. I guess that we can fix all these input format issues at once when we use the new way to initialize a `Particle` instance. There we can set all the different formats and set the variables which are included in a dictionary.

**Comment by NGoetz** [comment]
My current approach is to make the OSCARExtended format more flexible - fields which are not found should be set to None. That should be okay because so far we always added new fields in a new column add the end. Because it is very unlikely that new fields are added anytime soon, especially somewhere else than in a new column add the end, this should be the most elegant way.

**Comment by NGoetz** [comment]
Closed by #142
