### ISSUE TITLE
Speed up scripts

### ISSUE THREAD

**Issue by nilssass** [smash-transport/sparkx#134]
Search for places in the code that can be better handled in terms of computational time (use the power of AI here to get ideas)

Potential issues we found:
#### Oscar:
- We go through the complete file to get num_output_per_event, num_events, etc. and other stuff but without reading and for reading we go through it a second time

#### Useful:
- We may use seek to read single lines in a file e.g. for num_output_per_event. This seems to be much faster (~x20)

**Comment by NGoetz** [comment]
Currently we use up to 10 times more RAM than basic Oscar files occupy. We have to figure out why.

**Comment by Hendrik1704** [comment]
@NGoetz Here my opinion on your points:
1. I agree with you that giving up the Particle class wouldn't be good. It is very useful for data analysis to be able to compute all kinematic quantities of a particle by just calling the member functions. Giving this up would also require rewriting large parts of SPARKX (flow, density smearing,...).
2. I'm not sure if I understand your description correctly. Do you mean instead of storing
```
self.t_ = None
self.x_ = None
....
```
all in their own member variable, we would have one array containing all the quantities:
```
self.data_ = [t,x,...]
```
And then the member functions can access the corresponding entry in the array? And all the quantities which are not set are then still `None`?
