### ISSUE TITLE
Relax requirements

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/sparkx#318]
@RobinSattler found out that the installation problems related to the fastjet package can be solved by using a more recent version. @AxelKrypton pointed out that requirements of exact versions are to be avoided except for formatting and physics reasons.
Therefore, for the next release we should review the following requirements:

- Can the minimum requirement for fastjet be increased? Can we avoid demanding for an exact version?
- Can the abc-properties requirement be relaxed to allow for higher versions?
- Should the black requirement be fixed?

**Comment by RobinSattler** [comment]
Thanks for opening the issue, Niklas! Just for the sake of completeness, I attach the description of the fastjet problem I encountered.

As discussed a few days ago on slack, it seems that at least some python3.12 versions do not support the required fastjet version 3.4.1.3 (see [requirements.txt](https://github.com/smash-transport/sparkx/blob/main/requirements.txt)) and hence `pip install sparkx` fails (see attached screenshot with error message).                        
 
I tried this on my Mac (macOS Big Sur 11.7.10 with python 3.12.5, source of screenshot) and on my ITP machine (Ubuntu 24.04.1 LTS, python3.12.3). The `pip install` on my Mac failed, the one on the ITP machine succeeded. Since Niklas also encountered problems with this in the past, I don't think it's a problem caused by my Mac but rather a python version issue. Anyway, it might be interesting to bump fastjet up to version 3.4.2.x.
 
The related GitHub issue in the fastjet repo can be found [here](https://github.com/scikit-hep/fastjet/issues/293).
 
![sparkx-fastjet-error-python3-12](https://github.com/user-attachments/assets/1bd7c525-a967-494a-af44-7029e7ecff13)

**Comment by Hendrik1704** [comment]
I have just tested the package with fastjet 3.4.2.1 and the tests are still fine with this version. I think it's OK to increase the version requirement to `fastjet>=3.4.2.1` in the requirements.txt file.
For black it might be a good idea to fix the version, just in case they change some default format parameters in the future.
In the case of abc-properties I don't know if it makes sense to relax the requirement there. I just checked the pypi website and there the version 1.0 was released in 2020. It seems that there is no development ongoing for this package (see https://github.com/ndeutschmann/better_abc).

**Comment by NGoetz** [comment]
Okay, so then let's update fastjet and fix black. Regarding abc, you are absolutely right. Remind me to check in the next sprint if this dependency can maybe cancelled altogether. It is a non-maintained package and fixes Python issues from 6 years ago, maybe I can achieve the same using the standard library.

**Comment by NGoetz** [comment]
Fixed by #320
